import { Employee } from "@/types/employee";

export const employeedata: Employee[] = [
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
  {
    firstname: "Palash",
    lastname: "Das",
    email: "ib@m.com",
    roles: "Admin",
  },
];
