export const shopreviews = [
  {
    Shop_ID: "Shop A",
    ReviewID: 1,
    Review: "The shop has a great selection of products and friendly staff.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 2,
    Review: "I had a terrible experience. The service was very slow.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 3,
    Review: "The products are okay, but the prices are a bit high.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 4,
    Review: "Absolutely love this place! Highly recommend.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 5,
    Review: "Not satisfied with the customer service.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 6,
    Review: "Excellent quality and reasonable prices.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 7,
    Review: "The staff was rude and unhelpful.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 8,
    Review: "Very clean and well-maintained store.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 9,
    Review: "Long wait times at the checkout.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 10,
    Review: "Friendly and knowledgeable staff.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 11,
    Review: "Great shopping experience, will visit again.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 12,
    Review: "The store was out of stock on several items.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 13,
    Review: "Helpful staff and a wide variety of products.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 14,
    Review: "The service was very poor.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 15,
    Review: "I found everything I needed quickly and easily.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 16,
    Review: "Good prices and great service.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 17,
    Review: "The store was not clean and well-organized.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 18,
    Review: "The store layout is very intuitive and easy to navigate.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 19,
    Review: "Not happy with the quality of service.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 20,
    Review: "Love the atmosphere and the friendly staff.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 21,
    Review: "Terrible experience, will not be returning.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 22,
    Review: "Always a pleasure to shop here.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 23,
    Review: "The staff is very accommodating and helpful.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 24,
    Review: "An okay experience but nothing special.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop A",
    ReviewID: 25,
    Review: "Great place to find quality products.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 1,
    Review: "Excellent service and friendly staff.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 2,
    Review: "I had to wait a long time to get assistance.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 3,
    Review: "The products are okay, but the prices are a bit high.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 4,
    Review: "Had a very frustrating experience.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 5,
    Review: "Great selection of products at good prices.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 6,
    Review: "The service was unacceptable.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 7,
    Review: "Always a positive experience shopping here.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 8,
    Review: "Very poor customer service.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 9,
    Review: "The staff is very knowledgeable and helpful.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 10,
    Review: "Not a good place to shop.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 11,
    Review: "Highly recommend this store to others.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 12,
    Review: "The staff was not very helpful.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 13,
    Review: "Highly recommend this store for all your needs.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 14,
    Review: "Great quality and variety of products.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 15,
    Review: "Not a good selection of products.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 16,
    Review: "Great shopping experience, will visit again.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 17,
    Review: "I always find what I need here.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 18,
    Review: "An average store with decent products.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 19,
    Review: "Very dissatisfied with the service.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 20,
    Review: "Will not be coming back here.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 21,
    Review: "The best shopping experience I've had.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 22,
    Review: "Poor selection of products.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 23,
    Review: "The staff was not interested in helping customers.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 24,
    Review: "Some products are good but the service could improve.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop B",
    ReviewID: 25,
    Review: "Very disappointing shopping experience.",
    Sentiment: "Negative",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 1,
    Review: "The products are okay, but the prices are a bit high.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 2,
    Review: "A decent variety of items but not very organized.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 3,
    Review: "Good shopping experience overall.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 4,
    Review: "Found some great deals here.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 5,
    Review: "The staff is always friendly and helpful.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 6,
    Review: "An okay experience but nothing special.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 7,
    Review: "The store was average, not very impressive.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 8,
    Review: "Very clean and well-maintained store.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 9,
    Review: "The prices are reasonable but the service could be better.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 10,
    Review: "A mixed experience with some positives and negatives.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 11,
    Review: "An average store with decent products.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 12,
    Review: "Some products are good but the service could improve.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 13,
    Review: "Not bad but not great either.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 14,
    Review: "An okay shopping experience.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 15,
    Review: "Could be better with a few improvements.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 16,
    Review: "Great selection of products at good prices.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 17,
    Review: "Average experience with some good deals.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 18,
    Review: "Not bad but could use some improvements.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 19,
    Review: "A decent shopping experience.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 20,
    Review: "The prices are okay but the service could be better.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 21,
    Review: "The staff is very knowledgeable and helpful.",
    Sentiment: "Positive",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 22,
    Review: "Some products are good but the service could improve.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 23,
    Review: "Not a bad experience but not great either.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 24,
    Review: "An okay shopping experience overall.",
    Sentiment: "Neutral",
  },
  {
    Shop_ID: "Shop C",
    ReviewID: 25,
    Review: "Could be better with a few improvements.",
    Sentiment: "Neutral",
  },
];
